### ISSUE TITLE
Fecth async funtion

### ISSUE THREAD

**Issue by ushieru** [JazOki/Modular2#4]
Lo siento no hemos trabajado mucho con asincronía, pero intentare explicarlo lo mejor posible.
La función **Fetch** es asíncrona, por lo que llamar ambas al mismo tiempo no esperara a que una termine para realizar la otra, esto significa que ambas son disparadas al mismo tiempo. 

https://github.com/JazOki/Modular2/blob/0e0500fd03d75ad9019f030628c58e8c20cfb1fa/components/Layout.jsx#L35-L38

Recomiendo pasar de funciones síncronas a asíncronas, agrego ejemplo:

```js
const proyecto = async () => {
    try {
        var url = `/api/getproyectobyalumnoid?matricula=${matricula}`;
        const response = await fetch(url, {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json'
            }
        })
        const { proyectoE1Id } = await response.json()
        return proyectoE1Id;
    } catch (error) {
        console.log(error)
    }
}

const docente = async (proyectoE1Id) => {
    try {
        var url = `getdocentebyproyectid?proyectoE1Id=${proyectoE1Id}`;
        const response = await fetch(url, {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json'
            }
        })
        const json = await response.json()
        console.log(json)
    } catch (error) {
        console.log(error)
    }
}

useEffect(() => {
    proyecto()
        .then(proyectoE1Id => docente(proyectoE1Id))
}, [])
```

Quedo atento a cualquier duda que pueda surgir.

**Comment by Miri-HG** [comment]
Mmm me podria explicar los cambios que hizo?

**Comment by ushieru** [comment]
Aqui lo importante es mas como funciona la asincronia en JS. Y no hemos trabajado lo suficiente ese tema. Quiza hacer hacer algun quick course de youtube, o algun blog para entender un poco mas el tema.
Recomiendo: 
- https://www.youtube.com/watch?v=vn3tm0quoqE [ENG]
- https://www.youtube.com/watch?v=Q3HtXuDEy5s [ESP]

**Comment by ushieru** [comment]
En caso de no quedar claro lo podemos ver mañana en clases.

**Comment by Miri-HG** [comment]
El proyecto modular se entrega mañana, desconocemos a que hora será, por lo que dudamos en poder realizarlo mañana con usted, sin embargo, estaremos viendo y leyendo tutoriales para la solución, muchas gracias profesor.

**Comment by ushieru** [comment]
La solución tal cual la planteo aquí debería funcionarles sin problema, agrégala para salir del apuro y procuren llenar estas lagunas mentales estudiando un poco sobre los temas que no se terminan de entender. Lamentablemente 6 meses no es suficiente para dominar todos los aspectos de un lenguaje.
